const { chromium } = require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
(async()=>{ let out_pil; const b=await chromium.launch(); const ctx=await b.newContext(); const errs=[];
 const d=await ctx.newPage(); d.on('pageerror',e=>errs.push('D:'+e.message)); await d.setViewportSize({width:1440,height:900});
 await d.goto('file://'+process.cwd()+'/out/dashboard.html'); await d.evaluate(()=>localStorage.setItem('hk2dash:sesi',JSON.stringify({nama:'Rina Wijaya'}))); await d.reload(); await d.waitForTimeout(500);
 await d.evaluate(()=>{ state.view='event'; render(); document.querySelector('[data-hk-act="ev-new"]').click(); });
 await d.fill('[data-hk-bind="hk.evForm.nama"]','Bazar Ramadhan Bekasi');
 const today=await d.evaluate(()=>hkYmd(new Date())); await d.fill('[data-hk-bind="hk.evForm.mulai"]',today); await d.fill('[data-hk-bind="hk.evForm.selesai"]',today);
 await d.evaluate(()=>document.querySelector('[data-hk-act="evp-buka"]').scrollIntoView({block:'center'})); await d.screenshot({path:'shots/evtab-kosong.png'});
 await d.click('[data-hk-act="evp-buka"]'); await d.waitForTimeout(300);
 await d.fill('[data-hk-bind="hk.modal.cari"]','kaos burtuqol'); await d.waitForTimeout(200);
 const nCari=await d.locator('[data-hk-act="pil-cek"]').count();
 await d.click('[data-hk-act="pil-cek"][data-hk-arg="KBP-005-L"]');
 const autoCek=await d.evaluate(()=>document.querySelector("input[data-hk-act=pil-cek][data-hk-arg=KBP-005-L]").checked);
 const kolom=await d.evaluate(()=>[...document.querySelectorAll('.hk-modal thead th')].map(x=>x.innerText.trim()));
 await d.click('[data-hk-act="pil-cek"][data-hk-arg="KBP-005-XL"]');
 await d.fill('[data-hk-bind="hk.modal.cari"]','tumbler'); await d.waitForTimeout(200);
 await d.click('td[data-hk-act="pil-cek"][data-hk-arg="TMB-007"] >> nth=0');
 await d.fill('[data-hk-bind="hk.modal.cari"]',''); await d.waitForTimeout(200); await d.screenshot({path:'shots/evtab-pilih.png'});
 await d.click('[data-hk-act="pil-simpan"]'); await d.waitForTimeout(300);
 await d.fill('[data-hk-bind="hk.evForm.harga.TMB-007"]','79000');
 const tabel=await d.evaluate(()=>[...document.querySelectorAll('.hk-evtabel tbody tr')].map(r=>r.innerText.replace(/\s+/g,' ').trim()).slice(0,4));
 await d.evaluate(()=>document.querySelector('.hk-evtabel').scrollIntoView({block:'center'})); await d.screenshot({path:'shots/evtab-isi.png'});
 await d.click('[data-hk-act="ev-kasir"][data-hk-arg="Sari Handayani"]');
 await d.evaluate(()=>document.querySelector('[data-hk-act="ev-save"]').click()); await d.waitForTimeout(200);
 const tanpaPj=await d.evaluate(()=>document.querySelector('.toast')?.textContent);
 await d.selectOption('[data-hk-bind="hk.evForm.pj"]','Sari Handayani'); await d.screenshot({path:'shots/evpj-form.png'});
 await d.evaluate(()=>document.querySelector('[data-hk-act="ev-save"]').click()); await d.waitForTimeout(300);
 const pjInfo=await d.evaluate(()=>({pj:state.events.find(x=>x.nama==='Bazar Ramadhan Bekasi').pj, sub:document.querySelector('.page-sub').innerText.match(/Penanggung jawab: [^·]+/)?.[0]}));
 await d.click('[data-hk-act="alok-open"][data-hk-arg="kirim"] >> nth=0'); await d.waitForTimeout(200); await d.click('[data-hk-act="pil-buka"][data-hk-arg="alok"]'); await d.waitForTimeout(150);
 out_pil=await d.evaluate(()=>[...document.querySelectorAll('.hk-pilih tbody tr')].length); await d.click('[data-hk-act="pil-semua"]'); await d.click('[data-hk-act="pil-simpan"]'); await d.waitForTimeout(150);
 await d.fill('[data-hk-alok="KBP-005-L"]','10'); await d.fill('[data-hk-alok="TMB-007"]','6'); await d.click('[data-hk-act="alok-save"]'); await d.waitForTimeout(250);
 const ev=await d.evaluate(()=>{ const e=state.events.find(x=>x.nama==='Bazar Ramadhan Bekasi'); return {produk:e.produk, varian:e.varian, harga:e.harga, mut:state.mutasi.filter(m=>m.eventId===e.id).map(m=>m.status+':'+m.items.map(i=>i.sku+'x'+i.dikirim).join(','))}; });
 await d.screenshot({path:'shots/evprod-detail.png'});
 // edit: produk tetap terpilih
 await d.evaluate(()=>document.querySelector('[data-hk-act="ev-edit"]').click()); await d.waitForTimeout(200);
 const editProd=await d.evaluate(()=>state.hk.evForm.produk);
 // POS
 const p=await ctx.newPage(); p.on('pageerror',e=>errs.push('P:'+e.message)); await p.setViewportSize({width:390,height:844});
 await p.goto('file://'+process.cwd()+'/out/pos.html'); await p.waitForTimeout(600);
 await p.click('text=Rina'); for(const c of '111111') await p.click(`#hkLoginBody .pin-key:text-is("${c}")`); await p.waitForTimeout(400);
 if(await p.locator('#hkLoginBody .order-type-item:has-text("Bazar")').count()) await p.click('#hkLoginBody .order-type-item:has-text("Bazar")');
 await p.click('button:has-text("Buka Kasir")'); await p.waitForTimeout(500); await p.screenshot({path:'shots/evprod-pos.png'});
 const posProd=await p.evaluate(()=>PRODUCTS.map(x=>x.sku)); const harga=await p.evaluate(()=>PRODUCTS.find(x=>x.sku==='TMB-007').price);
 console.log(JSON.stringify({pilihanKirim:out_pil, kolom, nCari, autoCek, tabel, tanpaPj, pjInfo, ev, editProd, posProd, harga, errs})); await b.close(); })();
