const { chromium } = require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext(); const errs=[]; const out={};
 const base='file://'+process.cwd()+'/out/';
 const p=await ctx.newPage(); p.on('pageerror',e=>errs.push('P:'+e.message)); await p.setViewportSize({width:390,height:844});
 const toast=()=>p.evaluate(()=>document.querySelector('.toast,#toast').textContent);
 await p.goto(base+'pos.html'); await p.evaluate(()=>localStorage.clear()); await p.reload(); await p.waitForTimeout(500);
 await p.click('text=Sari Handayani'); for(const c of '333333') await p.click(`#hkLoginBody .pin-key:text-is("${c}")`); await p.waitForTimeout(500);
 const stok=()=>p.evaluate(()=>{ const it=JSON.parse(localStorage.getItem('hk2:stok')).find(x=>x.sku==='KP-004'); const po=it.perOutlet.find(o=>o.outlet==='Hikayat Fest Bandung'); return {akhir:po.akhir, rusak:po.rusak||0}; });
 await p.evaluate(()=>{ const id=PRODUCTS.find(x=>x.sku==='KP-004').id; addToCart(id); addToCart(id); addToCart(id); goToPayment(); selectPayment('cash'); cashTendered=billCtx().amountNow; prosesBayar(); }); await p.waitForTimeout(500);
 await p.evaluate(()=>{ try{ finishOrder(); }catch(e){} });
 const tid=await p.evaluate(()=>JSON.parse(localStorage.getItem('hk2:trx')).slice(-1)[0].id);
 const s0=await stok(); const kas0=await p.evaluate(()=>hkShiftKas(hkLoad(),hkLoad().shift.find(s=>s.id===JSON.parse(localStorage.getItem('hk2pos:sesi2')).shiftId)).harus);
 await p.evaluate(id=>{ hkBukaRiwayat(); setTimeout(()=>hkRwOpen(id),300); },tid); await p.waitForTimeout(700);
 out.tombol=await p.evaluate(()=>[...document.querySelectorAll('#hkTrxBody button')].map(x=>x.textContent.trim()));
 await p.click('#hkTrxBody button:has-text("Retur barang cacat")'); await p.waitForTimeout(500);
 await p.evaluate(()=>hkReturQty('KP-004',1)); await p.waitForTimeout(100);
 await p.evaluate(()=>hkReturSimpan()); out.tanpaAlasan=await toast();
 await p.fill('#hkRtAlasan','Sablon retak'); await p.evaluate(()=>rtAlasan(document.getElementById('hkRtAlasan')));
 await p.screenshot({path:'shots/retur-1.png'});
 await p.evaluate(()=>hkReturSimpan()); await p.waitForTimeout(500);
 out.supTerbuka=await p.evaluate(()=>document.getElementById('sheetHkSup').classList.contains('show'));
 for(const c of '222222') await p.evaluate(c=>hkSupKey(c),c); await p.waitForTimeout(400); out.toastTukar=await toast();
 const s1=await stok(); out.stokTukar={sebelum:s0, sesudah:s1};
 // retur kedua: uang kembali tunai
 await p.evaluate(id=>hkRwOpen(id),tid); await p.waitForTimeout(400); out.catatan=await p.evaluate(()=>[...document.querySelectorAll('#hkTrxBody .hk-note')].map(x=>x.innerText).join(' | ').slice(0,200));
 out.voidHilang=await p.evaluate(()=>!document.getElementById('hkVoidBtn'));
 await p.evaluate(id=>hkReturBuka(id),tid); await p.waitForTimeout(400);
 await p.evaluate(()=>{ hkReturSet('cara','Uang kembali'); hkReturQty('KP-004',1); hkReturQty('KP-004',1); hkReturQty('KP-004',1); }); out.maks=await toast();
 await p.fill('#hkRtAlasan','Jahitan lepas'); await p.evaluate(()=>rtAlasan(document.getElementById('hkRtAlasan')));
 await p.screenshot({path:'shots/retur-2.png'});
 await p.evaluate(()=>hkReturSimpan()); await p.waitForTimeout(400); for(const c of '111111') await p.evaluate(c=>hkSupKey(c),c); await p.waitForTimeout(400); out.toastUang=await toast();
 const s2=await stok(); out.stokUang=s2;
 const t=await p.evaluate(id=>JSON.parse(localStorage.getItem('hk2:trx')).find(x=>x.id===id),tid); out.retur=t.retur.map(r=>({no:r.no,cara:r.cara,nilai:r.nilai,disetujui:r.disetujui,items:r.items.map(i=>i.qty)}));
 const kas1=await p.evaluate(()=>hkShiftKas(hkLoad(),hkLoad().shift.find(s=>s.id===JSON.parse(localStorage.getItem('hk2pos:sesi2')).shiftId)).harus); out.kas={sebelum:kas0, sesudah:kas1};
 await p.evaluate(id=>hkRwOpen(id),tid); await p.waitForTimeout(300); out.tombolAkhir=await p.evaluate(()=>[...document.querySelectorAll('#hkTrxBody button')].map(x=>x.textContent.trim()));
 // dashboard
 const d=await ctx.newPage(); d.on('pageerror',e=>errs.push('D:'+e.message)); await d.setViewportSize({width:1440,height:900});
 await d.goto(base+'dashboard.html'); await d.evaluate(()=>localStorage.setItem('hk2dash:sesi',JSON.stringify({nama:'Rina Wijaya'}))); await d.reload(); await d.waitForTimeout(600);
 await d.evaluate(()=>{ state.view='lap-retur'; render(); }); await d.waitForTimeout(300); await d.screenshot({path:'shots/retur-dash.png'});
 out.kpi=await d.evaluate(()=>[...document.querySelectorAll('.main .metric-card')].map(x=>x.innerText.replace(/\n/g,' ')));
 out.sales=await d.evaluate(()=>{ const S=hkSales(hkLoad()).filter(x=>x.retur); return S.map(x=>({kotor:x.kotor,qty:x.qty,hpp:x.hpp})); });
 console.log(JSON.stringify({out,errs},null,1)); await b.close(); })();
