const { chromium } = require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
(async()=>{
  const b = await chromium.launch();
  const ctx = await b.newContext({viewport:{width:1440,height:900}});
  const p = await ctx.newPage();
  const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{ if(m.type()==='error') errs.push(m.text()); });
  await p.goto('file://'+process.cwd()+'/out/dashboard.html'); await p.evaluate(()=>localStorage.setItem('hk2dash:sesi',JSON.stringify({nama:'Dimas Pratama'}))); await p.reload(); await p.waitForTimeout(500);
  await p.waitForTimeout(500);
  const shot=async n=>{ await p.waitForTimeout(200); await p.screenshot({path:`shots/d-${n}.png`, fullPage:true}); };
  await shot('dashboard');
  const click=async sel=>{ await p.click(sel); await p.waitForTimeout(150); };
  await click('.nav-head[data-nav="event"]'); await shot('event-list');
  await click('[data-hk-act="ev-open"][data-hk-arg="ev-bdg"]'); await shot('event-detail');
  await click('[data-hk-act="alok-open"][data-hk-arg="kirim"]'); await click('[data-hk-act="alok-semua"]'); await shot('event-alok');
  await click('[data-hk-act="modal-close"]');
  await click('[data-hk-act="tutup-open"]'); await shot('event-tutup'); await click('[data-hk-act="modal-close"]');
  await p.evaluate(()=>{ state.view='lap-saluran'; state.openGroups.laporan=true; render(); }); await click('[data-hk-act="lap-per"][data-hk-arg="semua"]'); await shot('laporan-saluran');
  await click('.nav-child[data-nav="lap-event"]'); await shot('laporan-event');
  await click('.nav-head[data-nav="pengaturan-pos"]'); await shot('pengaturan');
  await p.evaluate(()=>{ state.view='produk-list'; render(); }); await shot('produk-list');
  await click('[data-hk-act="prod-new"]');
  await p.fill('[data-hk-bind="hk.prodForm.nama"]','Pin Enamel Hikayat');
  await p.selectOption('[data-hk-bind="hk.prodForm.kategori"]','Aksesoris');
  await p.fill('[data-hk-bind="hk.prodForm.sku"]','PIN-010');
  await p.fill('[data-hk-bind="hk.prodForm.modal"]','6000');
  await p.fill('[data-hk-bind="hk.prodForm.jual"]','20000');
  await p.fill('[data-hk-bind="hk.prodForm.stokAwal.p"]','100');
  await shot('produk-form');
  await click('[data-hk-act="prod-save"]'); await shot('produk-list-after');
  await p.evaluate(()=>{ state.view='karyawan'; render(); }); await shot('karyawan');
  await p.evaluate(()=>{ state.view='daftar-stok'; state.outletMode='single'; state.outlet='Hikayat Fest Bandung'; render(); }); await shot('stok-bdg');
  await p.evaluate(()=>{ state.view='pesanan-online'; state.outletMode='all'; render(); }); await shot('pesanan');
  await p.evaluate(()=>{ const i=state.marketplaceChannels.findIndex(c=>c.nama==='Shopee'); document.querySelector('[data-edit-marketplace="'+i+'"]')?.click(); }); await shot('marketplace-form');
  console.log('ERRORS', JSON.stringify(errs,null,1));
  await b.close();
})();
