const { chromium } = require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:1.5}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 const base='file://'+process.cwd()+'/out/'; await p.goto(base+'pos.html'); await p.waitForTimeout(600);
 const sh=async n=>{ await p.waitForTimeout(500); await p.screenshot({path:`shots/v10-${n}.png`}); };
 const LS=k=>p.evaluate(k=>JSON.parse(localStorage.getItem('hk2:'+k)),k);
 await p.click('text=Rina Wijaya'); for(const c of '111111') await p.click(`#hkLoginBody .pin-key:text-is("${c}")`);
 await p.click('#hkLoginBody .order-type-item:has-text("Kajian")'); await p.click('button:has-text("Buka Kasir")'); await p.waitForTimeout(400);
 await p.evaluate(()=>{ addToCart(PRODUCTS.find(x=>x.sku==='TMB-007').id); goToPayment(); }); await sh('01-wajib-pelanggan');
 const blocked=await p.evaluate(()=>!document.getElementById('view-pay').classList.contains('active'));
 await p.evaluate(()=>{ closeSheet('sheetPelangganList'); selectCustomer(customers.find(c=>c.name==='Fajar Ramadhan').code); goToPayment(); selectPayment('qris'); qrisConfirmed=true; prosesBayar(); finishOrder(); });
 const t=(await LS('trx')).slice(-1)[0];
 await p.evaluate(()=>{ hkBukaRiwayat(); }); await p.waitForTimeout(400); await p.evaluate(()=>hkRwScope('presale')); await sh('02-list');
 await p.evaluate(id=>hkRwOpen(id), t.id); await sh('03-detail');
 const moreHidden=await p.evaluate(()=>[...document.querySelectorAll('#moreMenu .quick-menu-item')].filter(x=>x.textContent.includes('Custom')).every(x=>x.style.display==='none'));
 // dashboard: tutup Kajian (tutup dulu kasir Rina), lalu refund
 const d=await ctx.newPage(); d.on('pageerror',e=>errs.push('D:'+e.message)); await d.setViewportSize({width:1440,height:900}); await d.goto(base+'dashboard.html'); await d.evaluate(()=>localStorage.setItem('hk2dash:sesi',JSON.stringify({nama:'Dimas Pratama'}))); await d.reload(); await d.waitForTimeout(500); await d.waitForTimeout(500);
 await d.evaluate(()=>{ state.view='presale'; render(); }); await d.screenshot({path:'shots/v10-d-presale.png'});
 await d.evaluate(()=>{ state.posShift.filter(s=>s.eventId==='ev-jkt'&&!s.tutup).forEach(s=>{ s.tutup=hkIso(new Date()); s.kasHitung=s.modal; }); state.hk.evId='ev-jkt'; state.view='event-detail'; render(); document.querySelector('[data-hk-act="tutup-open"]').click(); });
 await d.waitForTimeout(300); await d.screenshot({path:'shots/v10-d-tutup.png'});
 await d.evaluate(()=>document.querySelector('[data-hk-act="tutup-save"]').click()); await d.waitForTimeout(300);
 await d.evaluate(()=>{ state.view='presale'; state.hk.psTab='Perlu Refund'; render(); }); await d.screenshot({path:'shots/v10-d-perlu.png'});
 await d.evaluate(()=>document.querySelector('[data-hk-act="ps-refund"]').click()); await d.waitForTimeout(200);
 await d.fill('[data-hk-bind="hk.modal.bank"]','BCA'); await d.fill('[data-hk-bind="hk.modal.norek"]','1234567890'); await d.fill('[data-hk-bind="hk.modal.an"]','Nadia Putri');
 await d.screenshot({path:'shots/v10-d-refund.png'}); await d.evaluate(()=>document.querySelector('[data-hk-act="ps-refund-ok"]').click()); await d.waitForTimeout(300);
 await d.evaluate(()=>{ state.hk.psTab='Semua'; render(); }); await d.screenshot({path:'shots/v10-d-semua.png'});
 const sales=await d.evaluate(()=>hkSales(hkData()).filter(s=>s.eventId==='ev-jkt').length);
 await d.evaluate(()=>{ state.view='produk-list'; render(); document.querySelector('[data-hk-act="harga-open"][data-hk-arg="gudang"]').click(); }); await d.waitForTimeout(200);
 await d.evaluate(()=>{ state.hk.modal.harga['TOT-009']='42000'; document.querySelector('[data-hk-act="harga-save"]').click(); });
 const hg=await d.evaluate(()=>JSON.parse(localStorage.getItem('hk2:pos')).hargaGudang);
 const trxAll=await d.evaluate(()=>state.posTrx.filter(t=>t.pengambilan).map(t=>t.no+':'+t.status+'/'+t.pengambilan.status));
 console.log(JSON.stringify({blocked, peng:t.pengambilan, pel:t.pelanggan, moreHidden, sales, hg, trxAll, errs})); await b.close(); })();
