const { chromium } = require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
(async()=>{
  const b = await chromium.launch();
  const ctx = await b.newContext({viewport:{width:390,height:844}, deviceScaleFactor:2, isMobile:true, hasTouch:true});
  const p = await ctx.newPage();
  const errs=[]; p.on('pageerror',e=>errs.push('POS: '+e.message));
  const base='file://'+process.cwd()+'/out/';
  await p.goto(base+'pos.html'); await p.waitForTimeout(300);
  let i=0; const shot=async n=>{ await p.waitForTimeout(200); await p.screenshot({path:`shots/p-${String(++i).padStart(2,'0')}-${n}.png`}); };
  const tap=async sel=>{ await p.locator(sel).first().click(); await p.waitForTimeout(120); };
  const pin=async s=>{ for(const c of s) await tap(`.keys [data-v="${c}"]`); };
  await shot('login');
  await tap('[data-a="pick-kasir"][data-v="Sari Handayani"]'); await pin('33'); await shot('pin');
  await pin('33'); await shot('buka-shift');
  await tap('[data-a="modal-q"][data-v="200000"]');
  await tap('[data-a="buka-shift"]'); await shot('jual');
  await tap('[data-a="tap-produk"][data-v="KBP-005"]'); await tap('[data-a="add"][data-v="KBP-005-L"]'); await tap('[data-a="add"][data-v="KBP-005-L"]'); await tap('[data-a="add"][data-v="KBP-005-M"]'); await shot('varian');
  await tap('[data-a="sheet-close"]');
  await tap('[data-a="tap-produk"][data-v="TMB-007"]'); await shot('jual-isi');
  await tap('[data-a="keranjang"]');
  await tap('[data-a="diskon"]'); await tap('[data-a="dval"][data-v="15"]'); await tap('[data-a="diskon-ok"]'); await shot('pin-diskon');
  await pin('2222'); await shot('keranjang');
  await tap('[data-a="ke-bayar"]'); await shot('bayar-tunai');
  await tap('[data-a="uang"]:nth-child(2)'); await shot('bayar-tunai-isi');
  await tap('[data-a="metode"][data-v="QRIS"]'); await shot('bayar-qris');
  await tap('[data-a="metode"][data-v="Transfer"]'); await shot('bayar-transfer');
  await tap('[data-a="metode"][data-v="Tunai"]'); await tap('[data-a="uang"]:nth-child(2)');
  await tap('[data-a="selesai"]'); await shot('struk');
  await tap('[data-a="trx-baru"]');
  await tap('[data-a="tap-produk"][data-v="TOT-009"]'); await tap('[data-a="keranjang"]'); await tap('[data-a="ke-bayar"]'); await tap('[data-a="metode"][data-v="QRIS"]'); await tap('[data-a="selesai"]'); await tap('[data-a="trx-baru"]');
  await tap('[data-a="menu"]'); await shot('menu');
  await tap('[data-a="riwayat"]'); await shot('riwayat');
  await tap('[data-a="trx-detail"]'); await tap('[data-a="void-alasan"][data-v="Pembeli batal"]'); await shot('trx-detail');
  await tap('[data-a="void"]'); await pin('1111'); await shot('riwayat-void');
  await tap('[data-a="back-jual"]'); await tap('[data-a="menu"]'); await tap('[data-a="stok"]'); await shot('stok');
  await tap('[data-a="back-jual"]'); await tap('[data-a="menu"]'); await tap('[data-a="tutup"]');
  await p.locator('[data-in="kasHitung"]').fill('400000'); await p.locator('[data-in="kasHitung"]').dispatchEvent('input'); await shot('tutup');
  await tap('[data-a="tutup-ok"]'); await shot('ringkasan');
  // dashboard di tab lain, data sama
  const d = await ctx.newPage(); d.on('pageerror',e=>errs.push('DASH: '+e.message));
  await d.setViewportSize({width:1440,height:900});
  await d.goto(base+'dashboard.html'); await d.evaluate(()=>localStorage.setItem('hk2dash:sesi',JSON.stringify({nama:'Dimas Pratama'}))); await d.reload(); await d.waitForTimeout(500); await d.waitForTimeout(400);
  await d.evaluate(()=>{ state.hk.evId='ev-bdg'; state.view='event-detail'; render(); }); await d.waitForTimeout(200);
  await d.screenshot({path:'shots/d-after-pos.png', fullPage:true});
  // sinkron langsung: POS transaksi baru saat dashboard terbuka
  await p.bringToFront(); await tap('[data-a="logout"]'); await tap('[data-a="pick-kasir"][data-v="Budi Santoso"]'); await pin('4444'); await shot('budi-lanjut-shift');
  console.log('ERR', JSON.stringify(errs,null,1));
  await b.close();
})();
