const { chromium } = require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:1.5}); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.goto('file://'+process.cwd()+'/out/pos.html'); await p.waitForTimeout(600);
 await p.click('text=Budi Santoso'); for(const c of '444444') await p.click(`#hkLoginBody .pin-key:text-is("${c}")`); await p.waitForTimeout(600);
 const sh=async n=>{ await p.waitForTimeout(500); await p.screenshot({path:`shots/split-${n}.png`}); };
 const id=await p.evaluate(()=>{ const x=PRODUCTS.find(p=>p.sku==='KBP-005-S').id; addToCart(x); addToCart(x); goToPayment(); handlePisahBayarClick(); return x; });
 await p.waitForTimeout(400); await p.evaluate(()=>konfirmasiSimpanPisahBayar()); await p.waitForTimeout(500);
 await p.evaluate(()=>pilihSplitMode('produk')); await p.waitForTimeout(400); await p.evaluate(()=>konfirmasiPisahProdukInfo()); await p.waitForTimeout(400);
 const key='p'+id;
 await p.evaluate(k=>{ splitProdukQty(k,1,2); splitProdukQty(k,1,2); },key); await sh('produk');
 const r1=await p.evaluate(()=>({sel:splitProdukTotal(), dis:document.getElementById('btnProsesPisahProduk').disabled}));
 await p.evaluate(()=>{ closeSheet('sheetPisahProduk'); pilihSplitMode('jumlah'); }); await p.waitForTimeout(400);
 await p.evaluate(()=>{ '250000'.split('').forEach(splitKeyPress); }); await sh('jumlah-penuh');
 const r2=await p.evaluate(()=>document.getElementById('btnProsesPisahJumlah').disabled);
 await p.evaluate(()=>{ splitKeyClear(); '100000'.split('').forEach(splitKeyPress); }); await sh('jumlah-100');
 await p.evaluate(()=>{ prosesPisahJumlah(); }); await p.waitForTimeout(400);
 await p.evaluate(()=>{ selectPayment('qris'); prosesBayar(); }); await p.waitForTimeout(400); await p.fill('#hkQrisRef','1111'); await p.dispatchEvent('#hkQrisRef','input'); await p.click('#btnCekPembayaranQris'); await p.waitForTimeout(400); await sh('sukses-sebagian');
 const r3=await p.evaluate(()=>({held:HELD_ORDERS[0]&&{no:HELD_ORDERS[0].noTransaksi, paid:HELD_ORDERS[0].paidAmount, st:HELD_ORDERS[0].status}, trx:JSON.parse(localStorage.getItem('hk2:trx')).length}));
 await p.evaluate(()=>{ lunasiTagihanLangsung(); }); await p.waitForTimeout(500); await sh('lunasi');
 await p.evaluate(()=>{ selectPayment('qris'); prosesBayar(); }); await p.waitForTimeout(400); await p.fill('#hkQrisRef','2222'); await p.dispatchEvent('#hkQrisRef','input'); await p.click('#btnCekPembayaranQris'); await p.waitForTimeout(500);
 const r4=await p.evaluate(()=>{ const T=JSON.parse(localStorage.getItem('hk2:trx')); const t=T[T.length-1]; return {no:t.no, pesanan:t.noPesanan, total:t.total, metode:t.metode, bayar:t.pembayaran, held:HELD_ORDERS.length}; });
 console.log(JSON.stringify({r1,r2,r3,r4,errs})); await b.close(); })();
